export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const MY_TICKET_REQUEST = "MY_TICKET_REQUEST";
export const MY_TICKET_SUCCESS = "MY_TICKET_SUCCESS";
export const MY_TICKET_FAIL = "MY_TICKET_FAIL";

export const ALL_TICKET_REQUEST = "ALL_TICKET_REQUEST";
export const ALL_TICKET_SUCCESS = "ALL_TICKET_SUCCESS";
export const ALL_TICKET_FAIL = "ALL_TICKET_FAIL";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_RESET = "UPDATE_TICKET_RESET";
export const UPDATE_TICKET_FAIL = "UPDATE_TICKET_FAIL";

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_RESET = "DELETE_TICKET_RESET";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";

export const TICKET_DETAILS_REQUEST = "TICKET_DETAILS_REQUEST";
export const TICKET_DETAILS_SUCCESS = "TICKET_DETAILS_SUCCESS";
export const TICKET_DETAILS_FAIL = "TICKET_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
