export const ALL_TRAINS_SUCCESS = "ALL_TRAINS_SUCCESS";
export const ALL_TRAINS_FAIL = "ALL_TRAINS_FAIL";
export const ALL_TRAINS_REQUEST = "ALL_TRAINS_REQUEST";

export const ADMIN_TRAIN_REQUEST = "ADMIN_TRAIN_REQUEST";
export const ADMIN_TRAIN_SUCCESS = "ADMIN_TRAIN_SUCCESS";
export const ADMIN_TRAIN_FAIL = "ADMIN_TRAIN_FAIL";

export const TRAIN_DETAILS_REQUEST = "TRAIN_DETAILS_REQUEST";
export const TRAIN_DETAILS_SUCCESS = "TRAIN_DETAILS_SUCCESS";
export const TRAIN_DETAILS_FAIL = "TRAIN_DETAILS_FAIL";

export const DELETE_TRAIN_REQUEST = "DELETE_TRAIN_REQUEST";
export const DELETE_TRAIN_SUCCESS = "DELETE_TRAIN_SUCCESS";
export const DELETE_TRAIN_RESET = "DELETE_TRAIN_RESET";
export const DELETE_TRAIN_FAIL = "DELETE_TRAIN_FAIL";

export const UPDATE_TRAIN_REQUEST = "UPDATE_TRAIN_REQUEST";
export const UPDATE_TRAIN_SUCCESS = "UPDATE_TRAIN_SUCCESS";
export const UPDATE_TRAIN_RESET = "UPDATE_TRAIN_RESET";
export const UPDATE_TRAIN_FAIL = "UPDATE_TRAIN_FAIL";

export const NEW_TRAIN_REQUEST = "NEW_TRAIN_REQUEST";
export const NEW_TRAIN_SUCCESS = "NEW_TRAIN_SUCCESS";
export const NEW_TRAIN_RESET = "NEW_TRAIN_RESET";
export const NEW_TRAIN_FAIL = "NEW_TRAIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ADD_TO_BOOKING = "ADD_TO_BOOKING";
export const REMOVE_BOOKEDTRAIN = "REMOVE_BOOKEDTRAIN";
export const SAVE_BOOKEDTRAIN_INFO = "SAVE_BOOKEDTRAIN_INFO";
